### ISSUE TITLE
The cursor is hard to see

### ISSUE THREAD

**Issue by mohd874** [relastle/bluewery.vim#4] opened 2019-11-25 07:55 UTC
Thank you for creating a nice color for vim. 

I am using GVIM 8.0.586 on Win 10. I find it really hard to find the cursor in both normal and insert mode. To find the cursor, I have to switch to visual mode where it is more visible.

Keep the good work. I really like it.

**Comment by relastle** [comment] 2019-11-25 10:46
The problem is also reproduced in MacVim.

I was not able to notice such a critical bug because I use (Neo)Vim inside iterm2.

Thank you for the report, it will be fixed soon 🙏

**Closed** 2019-11-25 12:07 UTC
Labels: bug, enhancement

**Comment by relastle** [comment] 2019-11-25 12:09
Closed this issue because the problem seems to be fixed in https://github.com/relastle/bluewery.vim/pull/5

**Comment by mohd874** [comment] 2019-11-26 04:24
Thanks for quick response. I will start using it.

keep good work.
